### ISSUE TITLE
Error executing script

### ISSUE THREAD

**Issue by danipuertas2000** [zjoasan/netflix-install-script#7]
I've got this error executing the script:
```
./netflix_prep_install.sh: line 41: unexpected EOF while looking for matching `)'
./netflix_prep_install.sh: line 53: syntax error: unexpected end of file
osmc@osmc:~/addons/netflix-install-script-master$
```
Any help will be pleased

**Comment by zjoasan** [comment]
Sorry for this problem, that is what i get for editing the files when I was tired, missing ending ) in line 43, after wc -l,, and there is a : instead of ; after ]

Will update the script right now and you can download it again, remember to delete the first download first. Or wget will rename the new download .1 at the end.
